import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProviderWrapper from "@/app/ReduxProviderWrapper";

import { Toaster } from "react-hot-toast";
import GlobalAuthProvider from "./GlobleAuthProvider";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DocRef",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProviderWrapper>
          <GlobalAuthProvider>
             {children}
              <Toaster/> 
          </GlobalAuthProvider>
                        
          </ReduxProviderWrapper>
      </body>
    </html>
  );
}